language: go
go:
- 1.10
script:
- make
- echo '{}' | dist/j2y | dist/y2j
- make release
before_deploy:
- cd dist && sha256sum j2y-* > dist/SHA256SUMS
- cd dist && sha256sum y2j-* >> dist/SHA256SUMS
deploy:
  provider: releases
  api_key:
    secure: IvanXcfKZM9JTTcu/edWLYVLGVEkIw4Xo81p4DJ3jBlwF+dfFbbmB4mfVvrZfuI1/oOn9xZy39TMri80b+8QVTsfCto0CeIwWoQBeXYkpJBkcfo66m2iQ31H17QGJcpzD/ZHVm51nIwRZPUEmT66x5oZusZyrTm35w4xhbrXX221JlokBr/MT2Qz3HZTTlQ0acjJbVnmM/teXVPdkUk0huPbevfvGiQcpUSm7R9z7gZKvFPZZ/SjNc+mrs0ERIN2F9mMP2g3kZKScPBo5yUKfgm7HYesL9/NvM9w0lisdPoMBJKMgAfKzqpXcIox0s2EJW7XkcNoLNZy7Sqaz/99Xq+MV7kLZNUDl7myPnKvBrpVEmJi33zEslxunb2ez3hA1SLjjzueXay2+OW6PoWZ/Zc5XEIu3J/0bzw9b4m9hNqRTHbc1i8dEeVdEcmPSxv8j9LyoX3UCMlzUSnQHuxrDrDR4WK/1h2RW6+2DOifGVAhrH0pCWEuWjbl/gieot9a5ki/qwoPLoDe5CqEBtdBkGTtXbghI7X0wPq4RH/VsxWnakwyNI4G1MZDMV3M3mOR3XiB9BTtjX7u2C1SepAXPRsd+Yh4H7luUjBSC4hsWhmuiAHUkPm1xfKG1grpLLzBLeQNHNFc4zvuHGjP2MlCLRgu9usd8dLMY+mDP13153k=
  skip_cleanup: true
  file:
    - dist/j2y-linux-amd64
    - dist/y2j-linux-amd64
    - dist/j2y-darwin-amd64
    - dist/y2j-darwin-amd64
    - dist/SHA256SUMS
  on:
    repo: AstromechZA/j2y2j
    branch: master
